package wire

import (
	"encoding/binary"
	"fmt"

	"github.com/lestrrat-go/acidns/wire/wirebb"
)

// EDNS is the extension mechanism payload (RFC 6891) carried as the OPT
// pseudo-RR in the additional section. It surfaces the negotiated UDP
// payload size, version, extended RCODE, the DNSSEC OK flag, and any
// per-exchange options.
type EDNS interface {
	UDPSize() uint16
	ExtendedRCODE() uint8
	Version() uint8
	DO() bool
	Options() []EDNSOption
}

// EDNSOption is a single OPT RDATA option (code + data).
type EDNSOption interface {
	Code() uint16
	Data() []byte
}

// EDNS option codes (IANA registry, partial — most-commonly used here).
const (
	EDNSOptionLLQ          uint16 = 1  // RFC 8764
	EDNSOptionUL           uint16 = 2  // update lease
	EDNSOptionNSID         uint16 = 3  // RFC 5001
	EDNSOptionDAU          uint16 = 5  // RFC 6975 §3 — DNSSEC Algorithm Understood
	EDNSOptionDHU          uint16 = 6  // RFC 6975 §3 — DS Hash Understood
	EDNSOptionN3U          uint16 = 7  // RFC 6975 §3 — NSEC3 Hash Understood
	EDNSOptionClientSubnet uint16 = 8  // RFC 7871
	EDNSOptionExpire       uint16 = 9  // RFC 7314
	EDNSOptionCookie       uint16 = 10 // RFC 7873
	EDNSOptionTCPKeepalive uint16 = 11 // RFC 7828
	EDNSOptionPadding      uint16 = 12 // RFC 7830
	EDNSOptionChain        uint16 = 13 // RFC 7901
	EDNSOptionKeyTag       uint16 = 14 // RFC 8145
	EDNSOptionExtendedDNS  uint16 = 15 // RFC 8914 — Extended DNS Errors
)

// NewAlgorithmUnderstood builds an EDNS option for one of the RFC 6975
// signalling codes (DAU/DHU/N3U). The data carries the list of
// algorithm code points the requester can validate, in order.
func NewAlgorithmUnderstood(code uint16, algorithms ...uint8) (EDNSOption, error) {
	switch code {
	case EDNSOptionDAU, EDNSOptionDHU, EDNSOptionN3U:
	default:
		return nil, fmt.Errorf("%w: code %d is not DAU/DHU/N3U", ErrInvalidMessage, code)
	}
	data := append([]byte(nil), algorithms...)
	return ednsOption{code: code, data: data}, nil
}

// NewUpdateLease builds the "ul" EDNS option (code 2) used by Bonjour /
// DNS-SD dynamic update lease support (draft-sekar-dns-ul). The lease is
// a 32-bit unsigned seconds value attached to UPDATE messages so the
// server can expire records the requester forgets to refresh.
func NewUpdateLease(seconds uint32) EDNSOption {
	var b [4]byte
	binary.BigEndian.PutUint32(b[:], seconds)
	return ednsOption{code: EDNSOptionUL, data: b[:]}
}

// LLQOpcode names the long-lived-query operation (RFC 8764 §3).
type LLQOpcode uint16

const (
	LLQOpcodeSetup   LLQOpcode = 1
	LLQOpcodeRefresh LLQOpcode = 2
	LLQOpcodeEvent   LLQOpcode = 3
)

// LLQErrCode names a long-lived-query error (RFC 8764 §3).
type LLQErrCode uint16

const (
	LLQErrNoError    LLQErrCode = 0
	LLQErrServFull   LLQErrCode = 1
	LLQErrStatic     LLQErrCode = 2
	LLQErrFormErr    LLQErrCode = 3
	LLQErrNoSuchLLQ  LLQErrCode = 4
	LLQErrBadVers    LLQErrCode = 5
	LLQErrUnknownErr LLQErrCode = 6
)

// NewLLQ builds the long-lived-query EDNS option (code 1, RFC 8764). The
// llq-identifier is generated by the server during setup; clients pass 0
// on the initial Setup message and echo the server-supplied id on
// subsequent Refresh / Event messages.
func NewLLQ(opcode LLQOpcode, errCode LLQErrCode, llqID uint64, leaseSeconds uint32) EDNSOption {
	var b [18]byte
	binary.BigEndian.PutUint16(b[0:], 1) // version
	binary.BigEndian.PutUint16(b[2:], uint16(opcode))
	binary.BigEndian.PutUint16(b[4:], uint16(errCode))
	binary.BigEndian.PutUint64(b[6:], llqID)
	binary.BigEndian.PutUint32(b[14:], leaseSeconds)
	return ednsOption{code: EDNSOptionLLQ, data: b[:]}
}

type ednsOption struct {
	code uint16
	data []byte
}

func (o ednsOption) Code() uint16 { return o.code }
func (o ednsOption) Data() []byte { return o.data }

// NewEDNSOption returns an EDNS option. data is copied so the caller may
// reuse the slice.
func NewEDNSOption(code uint16, data []byte) (EDNSOption, error) {
	if len(data) > 0xffff {
		return nil, fmt.Errorf("%w: option data exceeds 65535 bytes", ErrInvalidMessage)
	}
	cp := make([]byte, len(data))
	copy(cp, data)
	return ednsOption{code: code, data: cp}, nil
}

type edns struct {
	udpSize  uint16
	extRCODE uint8
	version  uint8
	do       bool
	opts     []EDNSOption
}

func (e *edns) UDPSize() uint16       { return e.udpSize }
func (e *edns) ExtendedRCODE() uint8  { return e.extRCODE }
func (e *edns) Version() uint8        { return e.version }
func (e *edns) DO() bool              { return e.do }
func (e *edns) Options() []EDNSOption { return e.opts }

// EDNSBuilder constructs an EDNS payload. Like Builder, an EDNSBuilder
// is owned by a single goroutine and is NOT safe for concurrent use; the
// EDNS value returned by Build is immutable and may be shared.
type EDNSBuilder interface {
	UDPSize(uint16) EDNSBuilder
	ExtendedRCODE(uint8) EDNSBuilder
	Version(uint8) EDNSBuilder
	DO(bool) EDNSBuilder
	Option(EDNSOption) EDNSBuilder
	// Build returns the EDNS payload, or an error if validation
	// fails (e.g. duplicate EDNS option code).
	Build() (EDNS, error)
}

type ednsBuilder struct{ e edns }

// NewEDNSBuilder returns a fresh EDNSBuilder with sensible defaults
// (UDPSize=1232 — the IETF DNS Flag Day 2020 recommendation).
func NewEDNSBuilder() EDNSBuilder { return &ednsBuilder{e: edns{udpSize: 1232}} }

func (b *ednsBuilder) UDPSize(v uint16) EDNSBuilder      { b.e.udpSize = v; return b }
func (b *ednsBuilder) ExtendedRCODE(v uint8) EDNSBuilder { b.e.extRCODE = v; return b }
func (b *ednsBuilder) Version(v uint8) EDNSBuilder       { b.e.version = v; return b }
func (b *ednsBuilder) DO(v bool) EDNSBuilder             { b.e.do = v; return b }
func (b *ednsBuilder) Option(o EDNSOption) EDNSBuilder   { b.e.opts = append(b.e.opts, o); return b }
func (b *ednsBuilder) Build() (EDNS, error) {
	// Reject duplicate option codes — RFC 6891 §6.1.2 doesn't
	// expressly forbid them but the on-wire interpretation is
	// ambiguous and a well-formed payload should carry each option
	// at most once.
	seen := make(map[uint16]struct{}, len(b.e.opts))
	for _, o := range b.e.opts {
		c := o.Code()
		if _, dup := seen[c]; dup {
			return nil, fmt.Errorf("wire: duplicate EDNS option code %d", c)
		}
		seen[c] = struct{}{}
	}
	cp := b.e
	cp.opts = append([]EDNSOption(nil), b.e.opts...)
	return &cp, nil
}

// optTypeWire is the OPT pseudo-RR type code (RFC 6891 §6.1.2).
const optTypeWire uint16 = 41

func packOPT(p *wirebb.Packer, e EDNS) error {
	// NAME: root.
	p.Uint8(0)
	// TYPE: OPT.
	p.Uint16(optTypeWire)
	// CLASS: requestor's UDP payload size.
	p.Uint16(e.UDPSize())
	// TTL: extRCODE | version | DO | reserved
	ttl := uint32(e.ExtendedRCODE())<<24 | uint32(e.Version())<<16
	if e.DO() {
		ttl |= 1 << 15
	}
	p.Uint32(ttl)

	// RDLENGTH placeholder + options
	rdlenAt := p.Len()
	p.Uint16(0)
	start := p.Len()
	for _, o := range e.Options() {
		p.Uint16(o.Code())
		p.Uint16(uint16(len(o.Data())))
		p.Raw(o.Data())
	}
	end := p.Len()
	rdlen := end - start
	if rdlen > 0xffff {
		return fmt.Errorf("%w: OPT rdata exceeds 65535 bytes", ErrInvalidMessage)
	}
	buf := p.Bytes()
	binary.BigEndian.PutUint16(buf[rdlenAt:], uint16(rdlen))
	return nil
}

// unpackOPT decodes an already-positioned OPT pseudo-RR. It expects the
// unpacker to be at the start of a record whose type is OPT, and consumes
// the whole record.
func unpackOPT(u *wirebb.Unpacker) (EDNS, error) {
	// RFC 6891 §6.1.2 — OPT NAME MUST be the root domain (a single
	// zero-length octet). Accepting non-root names lets a broken or
	// hostile peer smuggle compression-pointer payloads into the OPT
	// owner field and pass them off as protocol-conformant.
	name, err := u.Name()
	if err != nil {
		return nil, err
	}
	if name.NumLabels() != 0 {
		return nil, fmt.Errorf("%w: OPT NAME must be root (RFC 6891 §6.1.2)", ErrInvalidMessage)
	}
	t, err := u.Uint16()
	if err != nil {
		return nil, err
	}
	if t != optTypeWire {
		return nil, fmt.Errorf("%w: expected OPT, got type %d", ErrInvalidMessage, t)
	}
	udpSize, err := u.Uint16()
	if err != nil {
		return nil, err
	}
	ttl, err := u.Uint32()
	if err != nil {
		return nil, err
	}
	rdlen, err := u.Uint16()
	if err != nil {
		return nil, err
	}
	if u.Remaining() < int(rdlen) {
		return nil, fmt.Errorf("%w: OPT rdata truncated", ErrInvalidMessage)
	}
	end := u.Off() + int(rdlen)

	e := &edns{
		udpSize:  udpSize,
		extRCODE: uint8(ttl >> 24),
		version:  uint8(ttl >> 16),
		do:       ttl&(1<<15) != 0,
	}
	for u.Off() < end {
		code, err := u.Uint16()
		if err != nil {
			return nil, err
		}
		l, err := u.Uint16()
		if err != nil {
			return nil, err
		}
		// Refuse option lengths that would walk past the OPT rdata window —
		// otherwise we'd silently consume bytes belonging to the next
		// additional record and reframe the rest of the message.
		if u.Off()+int(l) > end {
			return nil, fmt.Errorf("%w: OPT option length %d at off %d would exceed rdata window end %d",
				ErrInvalidMessage, l, u.Off(), end)
		}
		data, err := u.Bytes(int(l))
		if err != nil {
			return nil, err
		}
		cp := make([]byte, len(data))
		copy(cp, data)
		e.opts = append(e.opts, ednsOption{code: code, data: cp})
	}
	if u.Off() != end {
		return nil, fmt.Errorf("%w: OPT consumed %d bytes, rdlen was %d",
			ErrInvalidMessage, int(rdlen)-(end-u.Off()), rdlen)
	}
	return e, nil
}
